### ISSUE TITLE
Common cohesion principle etc

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/programming-principles#4]
Nice principles in these slides about horizontal vs vertical architecture https://www.slideshare.net/ChristianHujer/vertical-vs-horizontal-software-architecture-ruby-conf-india-2016-59817161?ref=https://www.slideshare.net/ChristianHujer.

**Comment by agarwal-deeksha** [comment]
@iluwatar Can you explain what this issue is?

**Comment by iluwatar** [comment]
Sorry, this really requires clarification. I'll close this issue and return with a new one later.
